name: kyc
description: A KYC.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2

  cross_file: ^0.3.3+2
  fluttertoast: ^8.0.9
  wakelock: ^0.6.2

  multi_kyc_sdk:
    git:
      url: https://github.com/MultiKYC/flutter_SDK.git


dependency_overrides:
  xml: 5.0.0
  camera: 0.10.0+1
  image: 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_utils: 2.6.1
  flutter_localizations:
    sdk: flutter

  lint: 1.8.2
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/