name: multi_kyc_sdk
description: KYC
version: 0.0.1+1
#homepage:

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # http
  http: 0.13.3
  intl: 0.17.0

  # json_serializable
  json_serializable: ^6.1.4

  # DI
  injectable: 1.5.3
  get_it: 7.2.0

  # MobX
  mobx: 2.0.6+1
  flutter_mobx: 2.0.4

  # ML
  google_mlkit_commons: 0.2.0
  google_mlkit_face_detection: 0.4.0
  learning_input_image: 0.0.6+2

  # image picker
  image_picker: 0.8.5+3

  # General
  image: 3.2.0
  path_provider: 2.0.11
  native_exif: 0.4.0

dependency_overrides:
  xml: 5.0.0
  camera: 0.10.0+1
  image: 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  lint: ^1.8.2

  # MobX
  build_runner: 2.1.10
  mobx_codegen: 2.0.5+2
  injectable_generator: 1.5.3

  # json_serializable
  json_serializable: 6.3.0
